site_name: Symblish
theme:
  name: material
  font:
    code: 'JetBrains Mono'
  features:
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 符号语:
    - 符号语简介: index.md
    - 本项目使用指南: contents.md